import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
// import "bootstrap/dist/js/bootstrap.min.js";
import Navbar from "./components/Navbar";
import Script from "next/script";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// import dynamic from "next/dynamic";
// const DynamicBootstrap = dynamic(
//   () => require("bootstrap/dist/js/bootstrap.min.js"),
//   { ssr: false }
// );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     require("bootstrap/dist/js/bootstrap");
  //   }
  // }, []);

  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
        {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></Script> */}
      </body>
    </html>
  );
}
